openapi: 3.0.0
info:
  description: The PingOne Platform API covering the PingOne Authorize service
  title: PingOne Platform API - Authorize
  version: 2023-06-29
externalDocs:
  description: PingOne Platform API Reference - Authorize APIs
  url: https://apidocs.pingidentity.com/pingone/platform/v1/api/#pingone-authorize
servers:
- description: PingOne Platform API Endpoint
  url: "{protocol}://{baseDomain}.{suffix}/v1"
  variables:
    suffix:
      default: com
      enum:
      - eu
      - com
      - asia
      - ca
    baseDomain:
      default: api.pingone
    protocol:
      default: https
- description: PingOne Platform API Endpoint
  url: "{protocol}://{baseHostname}/v1"
  variables:
    baseHostname:
      default: api.pingone.com
    protocol:
      default: https
security:
- bearer: []
tags:
- name: Policy Decision Management
- name: Policy Decision Authorization
- name: API Servers
paths:
  /environments/{environmentID}/decisionEndpoints:
    get:
      operationId: readAllDecisionEndpoints
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Conflict.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityArray'
          description: Successful response
      summary: READ All Decision Endpoints
      tags:
      - Policy Decision Management
    post:
      operationId: createDecisionEndpoint
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DecisionEndpoint'
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "405":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Conflict.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DecisionEndpoint'
          description: Successful response
      summary: CREATE Decision Endpoint
      tags:
      - Policy Decision Management
  /environments/{environmentID}/decisionEndpoints/{decisionEndpointID}:
    delete:
      operationId: deleteDecisionEndpoint
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: decisionEndpointID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Conflict.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "204":
          description: Successful response
      summary: DELETE Decision Endpoint
      tags:
      - Policy Decision Management
    get:
      operationId: readOneDecisionEndpoint
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: decisionEndpointID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Conflict.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DecisionEndpoint'
          description: Successful response
      summary: READ One Decision Endpoint
      tags:
      - Policy Decision Management
    put:
      operationId: updateDecisionEndpoint
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: decisionEndpointID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DecisionEndpoint'
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Conflict.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DecisionEndpoint'
          description: Successful response
      summary: UPDATE Decision Endpoint
      tags:
      - Policy Decision Management
  /environments/{environmentID}/apiServers:
    get:
      operationId: readAllAPIServers
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Conflict.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityArray'
          description: Successful response
      summary: READ All API Servers
      tags:
      - API Servers
    post:
      operationId: createAPIServer
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIServer'
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "405":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Conflict.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIServer'
          description: Successful response
      summary: CREATE API Server
      tags:
      - API Servers
  /environments/{environmentID}/apiServers/{apiServerID}:
    delete:
      operationId: deleteAPIServer
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: apiServerID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Conflict.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "204":
          description: Successful response
      summary: DELETE API Server
      tags:
      - API Servers
    get:
      operationId: readOneAPIServer
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: apiServerID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Conflict.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIServer'
          description: Successful response
      summary: READ One API Server
      tags:
      - API Servers
    put:
      operationId: updateAPIServer
      parameters:
      - explode: false
        in: path
        name: environmentID
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: apiServerID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIServer'
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: "Invalid request received.  Malformed JSON, malformed HTTP\
            \ request."
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request failed due to authorization issue.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Not found.
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Conflict.
        "429":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Request was rate limited
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P1Error'
          description: Uncaught error occurred.  Platform outage
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIServer'
          description: Successful response
      summary: UPDATE API Server
      tags:
      - API Servers
components:
  responses:
    "400":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: "Invalid request received.  Malformed JSON, malformed HTTP request."
    "401":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Request failed due to authorization issue.
    "403":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Request failed due to authorization issue.
    "404":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Not found.
    "405":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: "Invalid request received.  Malformed JSON, malformed HTTP request."
    "409":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Conflict.
    "429":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Request was rate limited
    "500":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/P1Error'
      description: Uncaught error occurred.  Platform outage
  schemas:
    LinksHATEOAS:
      additionalProperties: true
      example:
        next:
          href: https://openapi-generator.tech
        self:
          href: https://openapi-generator.tech
      properties:
        self:
          $ref: '#/components/schemas/LinksHATEOAS_self'
        next:
          $ref: '#/components/schemas/LinksHATEOAS_next'
      readOnly: true
      type: object
    LinksHATEOASHref:
      description: The URI of the resource.
      format: uri
      type: string
    APIServer:
      example:
        baseURLs:
        - baseURLs
        - baseURLs
        operations: "{}"
        _links:
          next:
            href: https://openapi-generator.tech
          self:
            href: https://openapi-generator.tech
        authorizationServer:
          resource:
            id: id
        name: name
        id: id
      properties:
        _links:
          $ref: '#/components/schemas/LinksHATEOAS'
        authorizationServer:
          $ref: '#/components/schemas/APIServer_authorizationServer'
        baseURLs:
          description: "An array of string that specifies the possible base URLs that\
            \ an end-user will use to access the APIs hosted on the customer's API\
            \ server. Multiple base URLs may be specified to support cases where the\
            \ same API may be available from multiple URLs (for example, from a user-friendly\
            \ domain URL and an internal domain URL). Base URLs must be valid absolute\
            \ URLs with the https or http scheme. If the path component is non-empty,\
            \ it must not end in a trailing slash. The path must not contain empty\
            \ backslash, dot, or double-dot segments. It must not have a query or\
            \ fragment present, and the host portion of the authority must be a DNS\
            \ hostname or valid IP (IPv4 or IPv6). The length must be less than or\
            \ equal to 256 characters."
          items:
            type: string
          type: array
        id:
          description: A string that specifies the resource's unique identifier.
          readOnly: true
          type: string
        name:
          description: "A string that specifies the API server resource name. The\
            \ name value must be unique among all API servers, and it must be a valid\
            \ resource name."
          type: string
        operations:
          description: "A map from the operation name to the operation object. Each\
            \ key must be valid ObjectName, and each value must be a valid operation.\
            \ Each key must be unique within the operations object, which means the\
            \ operation key is unique within an API server. No duplicate operation\
            \ values are allowed; operations with the same paths and methods members\
            \ are not allowed. The operations object is limited to 25 keys (25 individual\
            \ operations)."
          type: object
      required:
      - authorizationServer
      - baseURLs
      - name
      type: object
    EnumAPIServerPatternType:
      description: "A string that specifies the type of the pattern. Options are `EXACT`\
        \ ( the verbatim pattern is compared against the path from the request using\
        \ a case-sensitive comparison) and `PARAMETER` (the pattern is compared against\
        \ the path from the request using a case-sensitive comparison, using the syntax\
        \ below to encode wildcards and path segment captures.)"
      enum:
      - EXACT
      - PARAMETER
      type: string
    DecisionEndpoint:
      example:
        alternateId: alternateId
        provenance: provenance
        policyId: policyId
        _links:
          next:
            href: https://openapi-generator.tech
          self:
            href: https://openapi-generator.tech
        owned: true
        name: name
        authorizationVersion:
          id: id
          href: href
          title: title
          type: type
        description: description
        recordRecentRequests: true
        id: id
        recentDecisionsEnabled: true
        recentDecisions:
          href: href
          title: title
          type: type
      properties:
        _links:
          $ref: '#/components/schemas/LinksHATEOAS'
        alternateId:
          description: "A string that specifies alternative unique identifier for\
            \ the endpoint, which provides a method for locating the resource by a\
            \ known, fixed identifier."
          type: string
        authorizationVersion:
          $ref: '#/components/schemas/DecisionEndpoint_authorizationVersion'
        description:
          description: A string that specifies the description of the policy decision
            resource.
          type: string
        id:
          description: A string that specifies the resource’s unique identifier.
          readOnly: true
          type: string
        name:
          description: A string that specifies the policy decision resource name.
          type: string
        owned:
          description: A boolean that when true restricts modifications of the endpoint
            to PingOne-owned clients.
          type: boolean
        policyId:
          description: "A string that specifies the ID of the root policy configured\
            \ for this endpoint. If omitted, the policy editor service decides on\
            \ a suitable default."
          type: string
        provenance:
          description: A string that specifies a machine-readable identifier indicating
            the provenance of the current configuration. It has no meaning to the
            Policy Decision Service itself but exists to support integration with
            other services.
          type: string
        recentDecisionsEnabled:
          description: A boolean that specifies whether to show recent decisions.
          type: boolean
        recentDecisions:
          $ref: '#/components/schemas/DecisionEndpoint_recentDecisions'
        recordRecentRequests:
          description: "A boolean that specifies whether to record a limited history\
            \ of recent decision requests and responses, which can be queried through\
            \ a separate API."
          type: boolean
      required:
      - description
      - name
      - recordRecentRequests
      type: object
    EntityArray:
      example:
        size: 6.027456183070403
        _links:
          next:
            href: https://openapi-generator.tech
          self:
            href: https://openapi-generator.tech
        _embedded:
          decisionEndpoints:
          - alternateId: alternateId
            provenance: provenance
            policyId: policyId
            _links:
              next:
                href: https://openapi-generator.tech
              self:
                href: https://openapi-generator.tech
            owned: true
            name: name
            authorizationVersion:
              id: id
              href: href
              title: title
              type: type
            description: description
            recordRecentRequests: true
            id: id
            recentDecisionsEnabled: true
            recentDecisions:
              href: href
              title: title
              type: type
          - alternateId: alternateId
            provenance: provenance
            policyId: policyId
            _links:
              next:
                href: https://openapi-generator.tech
              self:
                href: https://openapi-generator.tech
            owned: true
            name: name
            authorizationVersion:
              id: id
              href: href
              title: title
              type: type
            description: description
            recordRecentRequests: true
            id: id
            recentDecisionsEnabled: true
            recentDecisions:
              href: href
              title: title
              type: type
          apiServers:
          - baseURLs:
            - baseURLs
            - baseURLs
            operations: "{}"
            _links:
              next:
                href: https://openapi-generator.tech
              self:
                href: https://openapi-generator.tech
            authorizationServer:
              resource:
                id: id
            name: name
            id: id
          - baseURLs:
            - baseURLs
            - baseURLs
            operations: "{}"
            _links:
              next:
                href: https://openapi-generator.tech
              self:
                href: https://openapi-generator.tech
            authorizationServer:
              resource:
                id: id
            name: name
            id: id
        count: 0.8008281904610115
      properties:
        _links:
          $ref: '#/components/schemas/LinksHATEOAS'
        _embedded:
          $ref: '#/components/schemas/EntityArray__embedded'
        count:
          type: number
        size:
          type: number
      type: object
    ObjectApplication:
      properties:
        id:
          description: A string that specifies the application resource ID associated
            with the object.
          readOnly: true
          type: string
      readOnly: true
      type: object
    ObjectEnvironment:
      properties:
        id:
          description: A string that specifies the environment associated with the
            object.
          readOnly: true
          type: string
      readOnly: true
      type: object
    ObjectOrganization:
      properties:
        id:
          description: A string that specifies the organization associated with the
            object.
          readOnly: true
          type: string
      readOnly: true
      type: object
    ObjectPopulation:
      properties:
        id:
          description: A string that specifies the population associated with the
            object.
          readOnly: true
          type: string
      readOnly: true
      type: object
    P1Error:
      properties:
        id:
          description: "A unique identifier that is stored in log files and always\
            \ included in an error response. This value can be used to track the error\
            \ received by the client, with server-side activity included for troubleshooting\
            \ purposes."
          type: string
        code:
          description: A general fault code which the client must handle to provide
            all exception handling routines and to localize messages for users. This
            code is common across all PingOne services and is human readable (such
            as a defined constant rather than a number).
          type: string
        message:
          description: A short description of the error. This message is intended
            to assist with debugging and is returned in English only.
          type: string
        details:
          description: Additional details about the error. Optional information to
            help resolve the error and to display to users.
          items:
            $ref: '#/components/schemas/P1Error_details_inner'
          type: array
      type: object
    LinksHATEOAS_self:
      description: An object that describes the current resource.
      example:
        href: https://openapi-generator.tech
      properties:
        href:
          description: The URI of the resource.
          format: uri
          type: string
      type: object
    LinksHATEOAS_next:
      description: An object that describes the next page of results. This property
        is present only if there is a next page of results and the `limit` parameter
        is used.
      example:
        href: https://openapi-generator.tech
      properties:
        href:
          description: The URI of the resource.
          format: uri
          type: string
      type: object
    APIServer_authorizationServer_resource:
      description: The resource defines the characteristics of the OAuth 2.0 access
        tokens used to get access to the APIs on the API server such as the audience
        and scopes.
      example:
        id: id
      properties:
        id:
          description: A string that specifies the UUID of the custom PingOne resource.
            This property must identify a PingOne resource with a type property value
            of CUSTOM.
          type: string
      required:
      - id
      type: object
    APIServer_authorizationServer:
      description: A container object for properties related to the authorization
        server that will issue access tokens used to access the APIs.
      example:
        resource:
          id: id
      properties:
        resource:
          $ref: '#/components/schemas/APIServer_authorizationServer_resource'
      required:
      - resource
      type: object
    DecisionEndpoint_authorizationVersion:
      example:
        id: id
        href: href
        title: title
        type: type
      properties:
        id:
          description: "A string that specifies the ID of the Authorization Version\
            \ deployed to this endpoint. Versioning allows independent development\
            \ and deployment of policies. If omitted, the endpoint always uses the\
            \ latest policy version available from the policy editor service."
          type: string
        href:
          description: A string that specifies the request URL for the authorization
            version endpoint.
          type: string
        title:
          description: A string that specifies the title for the authorization version
            response.
          type: string
        type:
          description: A string that specifies the content type for the authorization
            version response.
          type: string
      type: object
    DecisionEndpoint_recentDecisions:
      example:
        href: href
        title: title
        type: type
      properties:
        href:
          description: A string that specifies the request URL for the recent decisions
            endpoint.
          type: string
        title:
          description: A string that specifies the title for the recent decisions
            response.
          type: string
        type:
          description: A string that specifies the content type for the recent decisions
            response.
          type: string
      type: object
    EntityArray__embedded:
      example:
        decisionEndpoints:
        - alternateId: alternateId
          provenance: provenance
          policyId: policyId
          _links:
            next:
              href: https://openapi-generator.tech
            self:
              href: https://openapi-generator.tech
          owned: true
          name: name
          authorizationVersion:
            id: id
            href: href
            title: title
            type: type
          description: description
          recordRecentRequests: true
          id: id
          recentDecisionsEnabled: true
          recentDecisions:
            href: href
            title: title
            type: type
        - alternateId: alternateId
          provenance: provenance
          policyId: policyId
          _links:
            next:
              href: https://openapi-generator.tech
            self:
              href: https://openapi-generator.tech
          owned: true
          name: name
          authorizationVersion:
            id: id
            href: href
            title: title
            type: type
          description: description
          recordRecentRequests: true
          id: id
          recentDecisionsEnabled: true
          recentDecisions:
            href: href
            title: title
            type: type
        apiServers:
        - baseURLs:
          - baseURLs
          - baseURLs
          operations: "{}"
          _links:
            next:
              href: https://openapi-generator.tech
            self:
              href: https://openapi-generator.tech
          authorizationServer:
            resource:
              id: id
          name: name
          id: id
        - baseURLs:
          - baseURLs
          - baseURLs
          operations: "{}"
          _links:
            next:
              href: https://openapi-generator.tech
            self:
              href: https://openapi-generator.tech
          authorizationServer:
            resource:
              id: id
          name: name
          id: id
      properties:
        decisionEndpoints:
          items:
            $ref: '#/components/schemas/DecisionEndpoint'
          type: array
        apiServers:
          items:
            $ref: '#/components/schemas/APIServer'
          type: array
      type: object
    P1Error_details_inner_innerError:
      description: Additional details to help the client developer resolve the fault
        (primarily for UI validation reasons).
      properties:
        rangeMinimumValue:
          description: Errors that failed due to range violation. This attribute represents
            the minimum value of the range.
          type: integer
        rangeMaximumValue:
          description: The maximum range or value of an attribute.
          type: integer
        allowedPattern:
          description: A regex pattern describing an acceptable input pattern.
          type: string
        allowedValues:
          description: A list describing acceptable values.
          items:
            type: string
          type: array
        maximumValue:
          description: The maximum value allowed for the request.
          type: integer
        referencedValues:
          items:
            type: string
          type: array
      type: object
    P1Error_details_inner:
      properties:
        code:
          description: A general fault code which the client must handle to provide
            all exception handling routines and to localize messages for users. This
            code is common across all PingOne services and is human readable (such
            as a defined constant rather than a number).
          type: string
        target:
          description: The item that caused the error (such as a form field ID or
            an attribute inside a JSON object).
          type: string
        message:
          description: A short description of the error. This message is intended
            to assist with debugging and is returned in English only.
          type: string
        innerError:
          $ref: '#/components/schemas/P1Error_details_inner_innerError'
      type: object
  securitySchemes:
    bearer:
      bearerFormat: JWT
      description: OAuth bearer token (see documentation)
      scheme: bearer
      type: http
